# Generated by Django 4.0.4 on 2022-04-22 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('car_slug', models.SlugField(max_length=500, verbose_name='Slug')),
                ('car_title', models.CharField(max_length=200, verbose_name='Car Title')),
                ('customer_need', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('state', models.CharField(max_length=100, verbose_name='State')),
                ('message', models.TextField(verbose_name='Message')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
