# Generated by Django 4.0 on 2022-04-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_carmodel_options_alter_carmodel_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='doors',
            field=models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=10, verbose_name='Doors'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='fuel_type',
            field=models.CharField(max_length=100, verbose_name='Fuel Type'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='no_of_owners',
            field=models.CharField(max_length=100, verbose_name='No Of Owners'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='vin_no',
            field=models.CharField(max_length=100, verbose_name='Vin No'),
        ),
    ]
