# Generated by Django 4.0 on 2022-04-20 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_carmodel_color_alter_carmodel_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='price',
            field=models.FloatField(verbose_name='Price'),
        ),
    ]
