# Generated by Django 4.0 on 2022-04-20 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_alter_carmodel_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Price'),
        ),
    ]
